### PR TITLE
Debugger integration

### LINKED ISSUE #8: Add debugger to vscode extension
For now users have to manually type the command they want to run to start debugging e.g. `snforge test --debug --exact pkg::my_test` in `launch.json`

### LINKED ISSUE #90: Display errors that happen in debugger in vscode UI
Example error: lack of profiler/coverage/debugger debug info in sierra. Right now the process of the tool integrated with the debugger (e.g. snforge) hangs for some reason.

To be implemented in [vscode-cairo](https://github.com/software-mansion/vscode-cairo).

### PR DESCRIPTION
**Pull request by piotmag769**
Closes https://github.com/software-mansion/cairo-debugger/issues/8
Closes https://github.com/software-mansion/cairo-debugger/issues/90
---
**Stack**:
- #202
- #192
- #193 ⬅
---
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

File: src/debugger.ts [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+  constructor(private readonly debuggerLog: vscode.OutputChannel) {}
+
+  async createDebugAdapterDescriptor(
+    session: vscode.DebugSession,
+  ): Promise<vscode.DebugAdapterDescriptor | undefined | null> {
+    const config = new DebuggerSessionConfig(session.configuration);
+
+    const program_arg = config.get("program", "").trim();
+    if (program_arg === "") {
+      throw Error("Program property must be a non-empty string");
```
Comment (maciektr) [inline src/debugger.ts]: I don't undestand, where is this coming from? 🤔

File: src/debugger.ts [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+    const args = program_arg.split(/\s+/g);
+
+    const program = args.shift()!;
+    // Find the program in PATH. In case of failure treat it as a path to the executable.
+    const programAbsolutPathChecked = (await findToolInPath(program)) ?? (await checkTool(program));
+    if (programAbsolutPathChecked === undefined) {
+      throw Error(`configured program path does not exist or is not an executable: ${program}`);
+    }
+
+    const workspaceDir = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath ?? "";
```
Comment (maciektr) [inline src/debugger.ts:49]: Is this safe to just take the first one here? 🤔

File: src/debugger.ts (hunk 1 above)
Comment (piotmag769) [reply src/debugger.ts]: From `.vscode/launch.json` config. I know I marked `program` as required in `package.json`, but apparently it has no effect xD

File: src/debugger.ts (hunk 2 above)
Comment (piotmag769) [reply src/debugger.ts:49]: All workspace roots are even from vscode POV, so imo there is no better way than to take the first one as a fallback (and ppl usually have only one workspace open). Unless I can figure out from which `launch.json` the debugger was launched, but I believe I cannot get to this info (e.g. what if debugging was spawned via `spawnDebugger` method as response to `cairo/launchDebugger` - then you have no `launch.json` corresponding to the config).

Comment (piotmag769) [reply src/debugger.ts:49]: Actually, I have a better idea: I will make a default for `processCwd` - `${fileWorkspaceFolder}`, so that the vscode substition will do the work for me

Comment (piotmag769) [reply src/debugger.ts:49]: Nvm, I cannot - the `default` in `package.json` is ignored anyways xD So this is the best I can do

**Review by maciektr — APPROVED** [review]

File: src/debugger.ts [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+
+    this.debugAdapterProcesses.push(adapterProcess);
+
+    adapterProcess.stderr.on("data", (data: Buffer) => {
+      this.debuggerLog.append(data.toString());
+    });
+
+    const port = await this.waitForFreePort(adapterProcess.stdout);
+
+    return new vscode.DebugAdapterServer(port);
```
Comment (maciektr) [inline src/debugger.ts:72]: As discussed offline, consider adding some validation on the profiler config as a separate issue. This would enable us to show user a graphical error in the LS, as errors from snforge may not be easiest to decode. 
For reference: 

Image

**Review by maciektr — APPROVED** [review]

File: src/debugger.ts (hunk 3 above)
Comment (piotmag769) [reply src/debugger.ts:72]: https://github.com/software-mansion/cairo-debugger/issues/111
