### PR TITLE
Notify about errors and warnings via status bar

### LINKED ISSUE #87: Exclude "non-user-facing" request crashes from popups
### Problem

Sometimes the pop-ups can be annoying and debugging can be easier, although it makes the experience more frustrating for users that don't experience degrading of UX. 

### Proposed Solution

We disable popups on LS failures that are not actionable and don't cause LS to crash
All existing requests need to be reviewed and set-up in this way

_No response_

### Notes

_No response_

### PR DESCRIPTION
**Pull request by integraledelebesgue**
Closes #87 

## Changes
* Status bar indicates errors and warnings by changing its color
* Hover above the status bar shows the status of the language server and warnings/error messages
* Extension informs about critical, non-recoverable errors (e.g. proc macro server failure) via the status bar

## Preview
1. Status bar color (spinner spinner):
image

2. Error information:
image

### CODE REVIEW

File: src/context.ts [hunk 1]
```diff
@@ -18,11 +18,13 @@ export class Context {
 
   public readonly config: Config = new Config();
   public readonly statusBar: StatusBar;
+  // public readonly statusUpdateEmitter: vscode.EventEmitter<ServerStatus>;
```
Comment (Draggu) [inline src/context.ts:21]: ?

File: src/context.ts [hunk 2]
```diff
@@ -18,11 +18,13 @@ export class Context {
...
 
   private constructor(
     public readonly extension: vscode.ExtensionContext,
     public readonly log: RootLogOutputChannel,
   ) {
     this.statusBar = new StatusBar(this);
+    // this.statusUpdateEmitter = new vscode.EventEmitter<ServerStatus>();
```
Comment (Draggu) [inline src/context.ts:28]: ?

File: src/statusBar.ts [hunk 3]
```diff
@@ -12,14 +12,25 @@ const CAIRO_STATUS_BAR_TXT = "Cairo";
...
   private readonly statusBarItem: vscode.StatusBarItem;
   private client?: lc.LanguageClient | undefined;
+  private status: ServerStatus;
 
   constructor(private readonly context: Context) {
     this.statusBarItem = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left);
+    this.status = { health: "ok" };
 
     this.context.extension.subscriptions.push(this.statusBarItem);
+    // this.context.statusUpdateEmitter.event(async (status) => {
```
Comment (Draggu) [inline src/statusBar.ts:30]: ?

File: src/statusBar.ts [hunk 4]
```diff
@@ -123,12 +155,47 @@ export class StatusBar {
...
+    this.statusBarItem.backgroundColor = new vscode.ThemeColor("statusBar.background");
+  }
+
+  private setStatusBarColorWarning() {
+    this.statusBarItem.backgroundColor = new vscode.ThemeColor("statusBarItem.warningBackground");
+  }
+
+  private setStatusBarColorError() {
+    this.statusBarItem.backgroundColor = new vscode.ThemeColor("statusBarItem.errorBackground");
   }
```
Comment (Draggu) [inline src/statusBar.ts:199]: These are not reused and don't add much semantic. I think it could be inlined but up2you

File: src/cairols.ts [hunk 5]
```diff
@@ -16,12 +16,12 @@ import { projectConfigParsingFailed } from "./lspRequests";
...
 
 function notifyScarbMissing(ctx: Context) {
-  const errorMessage =
+  const message =
     "This is a Scarb project, but could not find Scarb executable on this machine. " +
     "Please add Scarb to the PATH environmental variable or set the 'cairo1.scarbPath' configuration " +
     "parameter. Otherwise Cairo code analysis will not work.";
-  void vscode.window.showWarningMessage(errorMessage);
-  ctx.log.error(errorMessage);
+  void ctx.statusBar.setStatus({ health: "warning", message: message });
```
Comment (Draggu) [inline src/cairols.ts:23]:
```suggestion
  void ctx.statusBar.setStatus({ health: "warning", message });
```

File: src/cairols.ts [hunk 6]
```diff
@@ -124,31 +125,18 @@ export async function setupLanguageServer(ctx: Context): Promise<SetupResult | u
...
-            const selectedValue = await vscode.window.showErrorMessage(
-              `Starting proc-macro-server failed ${retries} times in ${inMinutes} minutes, the proc-macro-server will not be restarted. Procedural macros will not be analyzed. See the output for more information`,
-              goToLogs,
-            );
-
-            if (selectedValue === goToLogs) {
-              client.outputChannel.show(true);
-            }
+            const message = `Starting proc-macro-server failed ${retries} times in ${inMinutes} minutes, the proc-macro-server will not be restarted. Procedural macros will not be analyzed. See the output for more information`;
+            await ctx.statusBar.setStatus({ health: "error", message: message });
```
Comment (Draggu) [inline src/cairols.ts:133]:
```suggestion
            await ctx.statusBar.setStatus({ health: "error", message });
```

File: src/cairols.ts [hunk 7]
```diff
@@ -161,6 +149,8 @@ export async function setupLanguageServer(ctx: Context): Promise<SetupResult | u
       new lc.NotificationType<string>("cairo/corelib-version-mismatch"),
       // eslint-disable-next-line @typescript-eslint/no-misused-promises
       async (errorMessage) => {
+        await ctx.statusBar.setStatus({ health: "error", message: errorMessage });
```
Comment (Draggu) [inline src/cairols.ts:152]:
```suggestion
        await ctx.statusBar.setStatus({ health: "error", message });
```

Please be consistent

File: src/cairols.ts [hunk 8]
```diff
@@ -192,16 +183,9 @@ export async function setupLanguageServer(ctx: Context): Promise<SetupResult | u
...
-          "`scarb metadata` failed. Check if your project builds correctly via `scarb build`.",
-          goToLogs,
-        );
-
-        if (selectedValue === goToLogs) {
-          client.outputChannel.show(true);
-        }
+        const message =
+          "`scarb metadata` failed. Check if your project builds correctly via `scarb build`.";
+        await ctx.statusBar.setStatus({ health: "error", message: message });
```
Comment (Draggu) [inline src/cairols.ts:188]:
```suggestion
        await ctx.statusBar.setStatus({ health: "error", message });
```

File: src/statusBar.ts [hunk 9]
```diff
@@ -123,12 +155,47 @@ export class StatusBar {
     const config = vscode.workspace.getConfiguration("cairo1");
     const showInStatusBar = config.get<boolean>("showInStatusBar", true);
 
-    if (showInStatusBar) {
-      await this.updateScarbVersion();
-      this.showStatusBarItem();
-    } else {
-      this.hideStatusBarItem();
+    if (!showInStatusBar) {
+      return;
```
Comment (Draggu) [inline src/statusBar.ts:159]:
```suggestion
      this.hideStatusBarItem();
      return;
```

File: src/cairols.ts [hunk 10]
```diff
@@ -211,16 +195,8 @@ export async function setupLanguageServer(ctx: Context): Promise<SetupResult | u
       projectConfigParsingFailed,
       // eslint-disable-next-line @typescript-eslint/no-misused-promises
       async (params) => {
-        const goToLogs = "Go to logs";
```
[the remark this answers is not in the document]
Comment (integraledelebesgue) [reply src/cairols.ts:214]: Logs can be accessed by clicking on the status bar, we don't lose too much functionality

File: src/statusBar.ts (hunk 4 above)
Comment (integraledelebesgue) [reply src/statusBar.ts]: Agree, I inlined these functions and those responsible for the bar visibility since they are useless too

**Review by Draggu — APPROVED** [review]

File: src/statusBar.ts [hunk 11]
```diff
@@ -123,19 +154,37 @@ export class StatusBar {
...
+      case "warning": {
+        backgroundColor = new vscode.ThemeColor("statusBarItem.warningBackground");
+        tooltip.appendText("Server status: OK").appendText(`\nWarning: ${status.message}`);
+        break;
+      }
+      case "error": {
+        backgroundColor = new vscode.ThemeColor("statusBarItem.errorBackground");
+        tooltip.appendText(`Server status: Error\n${status.message}`);
+        break;
+      }
```
Comment (Arcticae) [inline src/statusBar.ts:183]: We should probably disable the spinner here as well, wdyt?

**Review by Arcticae — APPROVED** [review]
